"""empty message

Revision ID: 4cac8b5a9716
Revises: 
Create Date: 2020-09-10 14:58:34.003643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cac8b5a9716'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('change_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('changed_field', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('model_ref', sa.String(), nullable=False),
    sa.Column('object_ref', sa.Integer(), nullable=False),
    sa.Column('date_recorded', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_data_model_ref'), 'change_data', ['model_ref'], unique=False)
    op.create_index(op.f('ix_change_data_object_ref'), 'change_data', ['object_ref'], unique=False)
    op.create_index(op.f('ix_change_data_user_id'), 'change_data', ['user_id'], unique=False)
    op.create_table('charging_station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charging_station_creator_id'), 'charging_station', ['creator_id'], unique=False)
    op.create_index(op.f('ix_charging_station_name'), 'charging_station', ['name'], unique=True)
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('name1', sa.String(), nullable=False),
    sa.Column('name2', sa.String(), nullable=True),
    sa.Column('name3', sa.String(), nullable=True),
    sa.Column('primary_phone_number', sa.String(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_creator_id'), 'person', ['creator_id'], unique=False)
    op.create_index(op.f('ix_person_name1'), 'person', ['name1'], unique=False)
    op.create_index(op.f('ix_person_name2'), 'person', ['name2'], unique=False)
    op.create_index(op.f('ix_person_name3'), 'person', ['name3'], unique=False)
    op.create_index(op.f('ix_person_primary_phone_number'), 'person', ['primary_phone_number'], unique=True)
    op.create_table('battery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('serial', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('voltage', sa.Integer(), nullable=False),
    sa.Column('charging_station_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['charging_station_id'], ['charging_station.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battery_charging_station_id'), 'battery', ['charging_station_id'], unique=False)
    op.create_index(op.f('ix_battery_creator_id'), 'battery', ['creator_id'], unique=False)
    op.create_index(op.f('ix_battery_serial'), 'battery', ['serial'], unique=True)
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('vin', sa.String(), nullable=False),
    sa.Column('battery_id', sa.Integer(), nullable=True),
    sa.Column('odometer_reading', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['battery_id'], ['battery.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_battery_id'), 'vehicle', ['battery_id'], unique=False)
    op.create_index(op.f('ix_vehicle_creator_id'), 'vehicle', ['creator_id'], unique=False)
    op.create_index(op.f('ix_vehicle_vin'), 'vehicle', ['vin'], unique=True)
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('date_started', sa.DateTime(), nullable=False),
    sa.Column('date_ended', sa.DateTime(), nullable=True),
    sa.Column('current_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['current_vehicle_id'], ['vehicle.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_creator_id'), 'driver', ['creator_id'], unique=False)
    op.create_index(op.f('ix_driver_current_vehicle_id'), 'driver', ['current_vehicle_id'], unique=False)
    op.create_index(op.f('ix_driver_date_ended'), 'driver', ['date_ended'], unique=False)
    op.create_index(op.f('ix_driver_date_started'), 'driver', ['date_started'], unique=False)
    op.create_index(op.f('ix_driver_person_id'), 'driver', ['person_id'], unique=False)
    op.create_table('battery_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('battery_in_id', sa.Integer(), nullable=True),
    sa.Column('battery_out_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('charging_station_id', sa.Integer(), nullable=True),
    sa.Column('battery_in_energy', sa.Integer(), nullable=True),
    sa.Column('battery_out_energy', sa.Integer(), nullable=True),
    sa.Column('odometer_reading', sa.Integer(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=True),
    sa.Column('correction_id', sa.Integer(), nullable=True),
    sa.Column('last_transaction_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['battery_in_id'], ['battery.id'], ),
    sa.ForeignKeyConstraint(['battery_out_id'], ['battery.id'], ),
    sa.ForeignKeyConstraint(['charging_station_id'], ['charging_station.id'], ),
    sa.ForeignKeyConstraint(['correction_id'], ['battery_transaction.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['last_transaction_id'], ['battery_transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battery_transaction_battery_in_id'), 'battery_transaction', ['battery_in_id'], unique=False)
    op.create_index(op.f('ix_battery_transaction_battery_out_id'), 'battery_transaction', ['battery_out_id'], unique=False)
    op.create_index(op.f('ix_battery_transaction_charging_station_id'), 'battery_transaction', ['charging_station_id'], unique=False)
    op.create_index(op.f('ix_battery_transaction_correction_id'), 'battery_transaction', ['correction_id'], unique=False)
    op.create_index(op.f('ix_battery_transaction_creator_id'), 'battery_transaction', ['creator_id'], unique=False)
    op.create_index(op.f('ix_battery_transaction_driver_id'), 'battery_transaction', ['driver_id'], unique=False)
    op.create_index(op.f('ix_battery_transaction_last_transaction_id'), 'battery_transaction', ['last_transaction_id'], unique=False)
    op.create_index(op.f('ix_battery_transaction_transaction_date'), 'battery_transaction', ['transaction_date'], unique=False)
    op.create_table('driver_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('ride_distance', sa.Integer(), nullable=False),
    sa.Column('energy_used', sa.Integer(), nullable=False),
    sa.Column('cumulative_ride_distance', sa.Integer(), nullable=False),
    sa.Column('cumulative_energy_used', sa.Integer(), nullable=False),
    sa.Column('last_transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['last_transaction_id'], ['battery_transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_summary_driver_id'), 'driver_summary', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_summary_end_date'), 'driver_summary', ['end_date'], unique=False)
    op.create_index(op.f('ix_driver_summary_start_date'), 'driver_summary', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_driver_summary_start_date'), table_name='driver_summary')
    op.drop_index(op.f('ix_driver_summary_end_date'), table_name='driver_summary')
    op.drop_index(op.f('ix_driver_summary_driver_id'), table_name='driver_summary')
    op.drop_table('driver_summary')
    op.drop_index(op.f('ix_battery_transaction_transaction_date'), table_name='battery_transaction')
    op.drop_index(op.f('ix_battery_transaction_last_transaction_id'), table_name='battery_transaction')
    op.drop_index(op.f('ix_battery_transaction_driver_id'), table_name='battery_transaction')
    op.drop_index(op.f('ix_battery_transaction_creator_id'), table_name='battery_transaction')
    op.drop_index(op.f('ix_battery_transaction_correction_id'), table_name='battery_transaction')
    op.drop_index(op.f('ix_battery_transaction_charging_station_id'), table_name='battery_transaction')
    op.drop_index(op.f('ix_battery_transaction_battery_out_id'), table_name='battery_transaction')
    op.drop_index(op.f('ix_battery_transaction_battery_in_id'), table_name='battery_transaction')
    op.drop_table('battery_transaction')
    op.drop_index(op.f('ix_driver_person_id'), table_name='driver')
    op.drop_index(op.f('ix_driver_date_started'), table_name='driver')
    op.drop_index(op.f('ix_driver_date_ended'), table_name='driver')
    op.drop_index(op.f('ix_driver_current_vehicle_id'), table_name='driver')
    op.drop_index(op.f('ix_driver_creator_id'), table_name='driver')
    op.drop_table('driver')
    op.drop_index(op.f('ix_vehicle_vin'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_creator_id'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_battery_id'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_battery_serial'), table_name='battery')
    op.drop_index(op.f('ix_battery_creator_id'), table_name='battery')
    op.drop_index(op.f('ix_battery_charging_station_id'), table_name='battery')
    op.drop_table('battery')
    op.drop_index(op.f('ix_person_primary_phone_number'), table_name='person')
    op.drop_index(op.f('ix_person_name3'), table_name='person')
    op.drop_index(op.f('ix_person_name2'), table_name='person')
    op.drop_index(op.f('ix_person_name1'), table_name='person')
    op.drop_index(op.f('ix_person_creator_id'), table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_charging_station_name'), table_name='charging_station')
    op.drop_index(op.f('ix_charging_station_creator_id'), table_name='charging_station')
    op.drop_table('charging_station')
    op.drop_index(op.f('ix_change_data_user_id'), table_name='change_data')
    op.drop_index(op.f('ix_change_data_object_ref'), table_name='change_data')
    op.drop_index(op.f('ix_change_data_model_ref'), table_name='change_data')
    op.drop_table('change_data')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
